### ISSUE TITLE
[PANIC] 動かし続けると次第に遅くなり最終的にPanicする

### ISSUE THREAD

**Issue by hyoi** [hyoi/falls#1]
heron 0.7.0が内部で利用しているrapier2d 0.8.0の中でPANICする。
次第に遅くなる様子から、何かしらのリークが原因だと思う。
```
PS C:\XXXXX\windows_rust\bevy0.5\inseki> cargo run --release
    Finished release [optimized] target(s) in 0.56s
     Running `target\release\inseki.exe`
thread 'Compute Task Pool (0)' panicked at 'assertion failed: proxy.aabb.maxs[dim] >= self.min_bound', C:\XXXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\rapier2d-0.8.0\src\geometry\broad_phase_multi_sap\sap_axis.rs:55:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\XXXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368:45       
error: process didn't exit successfully: `target\release\inseki.exe` (exit code: 0xc000041d)
PS C:\XXXXX\windows_rust\bevy0.5\inseki>
```
画面外に出た落下物(Entity)をbevyの標準的な方法で解放しているが(cmds.entity( id ).despawn();)、それだとheron関係の何かが解放されないとか？

**Comment by hyoi** [comment]
【メモ】エラーメッセージ`assertion failed: proxy.aabb.maxs[dim] >= self.min_bound`に関連した情報。
- [The simulation panics!](https://rapier.rs/docs/user_guides/rust_bevy_plugin/common_mistakes/#the-simulation-panics)
- [Far away object causes panic in broad phase #77](https://github.com/dimforge/rapier/issues/77)

**Comment by hyoi** [comment]
落下物をdespawn、spawnするのをやめ、spawn済みの落下物を繰り返し再利用するように変更した。
数時間動かし続けても現象が再発しないため、不具合の回避策として有効と判定。
本件はクローズ。
